### PR TITLE
Point to latest docs

### PR DESCRIPTION
**Pull request by alanocallaghan**

### CODE REVIEW

**Comment by petebankhead** [comment]
Should be stable I think? Latest can be pre-release

**Comment by petebankhead** [comment]
Or else should be the version compatible with the template, so 0.5 here (I guess that was probably the logic previously)

**Comment by alanocallaghan** [comment]
Could be, I certainly trust you over me. I'd be inclined to say stable, because otherwise we'll forget to update (again)

**Comment by petebankhead** [comment]
Yeah, I'd be inclined to say 0.5... except that we will definitely forget to update it again, so stable is fine with me.

**Pull request merged**
